-- seed.sql — runs only on local `supabase db reset` / `supabase db start`,
-- NOT on `supabase db push`.
--
-- The global tag vocabulary (tag_categories + tags) now lives in migration
-- 0003_seed_vocabulary.sql so it deploys to the live project too. Keep this file
-- for any local-only convenience data; it is intentionally empty for now.
